/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSimuladosRouteImport } from './routes/_authenticated/simulados'
import { Route as AuthenticatedRedacaoRouteImport } from './routes/_authenticated/redacao'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated/planos'
import { Route as AuthenticatedIaRouteImport } from './routes/_authenticated/ia'
import { Route as AuthenticatedDesempenhoRouteImport } from './routes/_authenticated/desempenho'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as AuthenticatedSimuladoIdRouteImport } from './routes/_authenticated/simulado.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSimuladosRoute = AuthenticatedSimuladosRouteImport.update({
  id: '/simulados',
  path: '/simulados',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRedacaoRoute = AuthenticatedRedacaoRouteImport.update({
  id: '/redacao',
  path: '/redacao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIaRoute = AuthenticatedIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesempenhoRoute = AuthenticatedDesempenhoRouteImport.update({
  id: '/desempenho',
  path: '/desempenho',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSimuladoIdRoute = AuthenticatedSimuladoIdRouteImport.update({
  id: '/simulado/$id',
  path: '/simulado/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/app': typeof AuthenticatedAppRoute
  '/desempenho': typeof AuthenticatedDesempenhoRoute
  '/ia': typeof AuthenticatedIaRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/redacao': typeof AuthenticatedRedacaoRoute
  '/simulados': typeof AuthenticatedSimuladosRoute
  '/simulado/$id': typeof AuthenticatedSimuladoIdRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/app': typeof AuthenticatedAppRoute
  '/desempenho': typeof AuthenticatedDesempenhoRoute
  '/ia': typeof AuthenticatedIaRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/redacao': typeof AuthenticatedRedacaoRoute
  '/simulados': typeof AuthenticatedSimuladosRoute
  '/simulado/$id': typeof AuthenticatedSimuladoIdRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/desempenho': typeof AuthenticatedDesempenhoRoute
  '/_authenticated/ia': typeof AuthenticatedIaRoute
  '/_authenticated/planos': typeof AuthenticatedPlanosRoute
  '/_authenticated/redacao': typeof AuthenticatedRedacaoRoute
  '/_authenticated/simulados': typeof AuthenticatedSimuladosRoute
  '/_authenticated/simulado/$id': typeof AuthenticatedSimuladoIdRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/admin'
    | '/app'
    | '/desempenho'
    | '/ia'
    | '/planos'
    | '/redacao'
    | '/simulados'
    | '/simulado/$id'
    | '/api/public/stripe-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/admin'
    | '/app'
    | '/desempenho'
    | '/ia'
    | '/planos'
    | '/redacao'
    | '/simulados'
    | '/simulado/$id'
    | '/api/public/stripe-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/desempenho'
    | '/_authenticated/ia'
    | '/_authenticated/planos'
    | '/_authenticated/redacao'
    | '/_authenticated/simulados'
    | '/_authenticated/simulado/$id'
    | '/api/public/stripe-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/simulados': {
      id: '/_authenticated/simulados'
      path: '/simulados'
      fullPath: '/simulados'
      preLoaderRoute: typeof AuthenticatedSimuladosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/redacao': {
      id: '/_authenticated/redacao'
      path: '/redacao'
      fullPath: '/redacao'
      preLoaderRoute: typeof AuthenticatedRedacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ia': {
      id: '/_authenticated/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof AuthenticatedIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/desempenho': {
      id: '/_authenticated/desempenho'
      path: '/desempenho'
      fullPath: '/desempenho'
      preLoaderRoute: typeof AuthenticatedDesempenhoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/simulado/$id': {
      id: '/_authenticated/simulado/$id'
      path: '/simulado/$id'
      fullPath: '/simulado/$id'
      preLoaderRoute: typeof AuthenticatedSimuladoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedDesempenhoRoute: typeof AuthenticatedDesempenhoRoute
  AuthenticatedIaRoute: typeof AuthenticatedIaRoute
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRoute
  AuthenticatedRedacaoRoute: typeof AuthenticatedRedacaoRoute
  AuthenticatedSimuladosRoute: typeof AuthenticatedSimuladosRoute
  AuthenticatedSimuladoIdRoute: typeof AuthenticatedSimuladoIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedDesempenhoRoute: AuthenticatedDesempenhoRoute,
  AuthenticatedIaRoute: AuthenticatedIaRoute,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRoute,
  AuthenticatedRedacaoRoute: AuthenticatedRedacaoRoute,
  AuthenticatedSimuladosRoute: AuthenticatedSimuladosRoute,
  AuthenticatedSimuladoIdRoute: AuthenticatedSimuladoIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
